apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: browserless-chromium-service
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/minScale: '1'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 3600
      containers:
      - name: browserless-chromium-service
        image: >-
          asia-southeast1-docker.pkg.dev/multi-gke-ops/gke-repo/browserless-chrome:v1
        ports:
        - name: http1
          containerPort: 3000
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 3000
