apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: media-gen
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 10
      timeoutSeconds: 600
      containers:
      - name: media-gen
        image: media-gen
        env:
          # - name: TZ
          #   value: "Asia/Singapore"
          - name: APP_NAME
            value: "media-gen"
        ports:
        - name: http1
          containerPort: 7860
        resources:
          limits:
            cpu: 4000m
            memory: 16Gi
        volumeMounts:
          - name: in-memory-storage
            mountPath: /workspace/tmp
        startupProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 3
          tcpSocket:
            port: 7860
      volumes:
      - name: in-memory-storage
        emptyDir:
          medium: Memory
          sizeLimit: 4G

