apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rrd-console
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 1
      timeoutSeconds: 300
      containers:
      - name: rrd-console
        image: rrd-console
        env:
          # - name: TZ
          #   value: "Asia/Singapore"
          - name: APP_NAME
            value: "rrd-console"
        ports:
        - name: http1
          containerPort: 7860
        resources:
          limits:
            cpu: 2
            memory: 4096Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 3
          tcpSocket:
            port: 7860

