apiVersion: skaffold/v4beta13
kind: Config
build:
  platforms:
    - linux/amd64
    - linux/arm64
  tagPolicy:
    customTemplate:
      # template: "{{env \"RELEASE_TAG\"}}-{{.GIT_COMMIT_SHORT}}"
      template: "v1-{{.GIT_COMMIT_SHORT}}"
      components: # Define components used in the template
       - name: GIT_COMMIT_SHORT
         gitCommit:
           prefix: "" # Optional prefix
           variant: AbbrevCommitSha # Use abbreviated commit SHA

  artifacts:
  - image: asia-southeast1-docker.pkg.dev/multi-gke-ops/gke-repo/media-gen
    context: .
    docker:
      dockerfile: Dockerfile

    #   # builder: "gcr.io/buildpacks/builder:v1"
    #   builder: "paketobuildpacks/builder-jammy-full"
    #   env:
    #     # - "GOOGLE_APPLICATIONS_PACKAGES=ffmpeg,ffprobe"
    #     - "BP_APT_PACKAGES=ffmpeg"

manifests:
  kustomize:
    paths:
      - resources

deploy:
  cloudrun:
    projectid: multi-gke-ops
    region: us-central1

profiles:
- name: gcb
  build:
    googleCloudBuild: {}