apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: match

resources:
- analysis-service.yaml

images:
- name: "analysis-service"
  newName: asia-southeast1-docker.pkg.dev/multi-gke-ops/gke-repo/analysis-service
  newTag: latest

patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: PROJECT_ID
        value: "multi-gke-ops"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: LOCATION
        value: "us-central1"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: MODEL_ID
        value: "claude-3-5-sonnet-v2@20241022"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: MODEL_LOCATION
        value: "us-east5"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: BATCH_MODEL_ID
        value: "gemini-1.5-pro-002"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: BATCH_MODEL_LOCATION
        value: "us-central1"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: ANALYSIS_GCS_BUCKET
        value: "rrd-sentiment-analysis-multi-gke-ops"

  target:
    kind: Service

