apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: match

resources:
- nexus-service.yaml

images:
- name: "nexus-service"
  newName: asia-southeast1-docker.pkg.dev/multi-gke-ops/gke-repo/nexus-service
  newTag: latest
