apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nexus-service
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - name: nexus-service
        image: nexus-service
        env:
          # - name: TZ
          #   value: "Asia/Singapore"
          - name: RRD_JOB_IMAGE
            value: "asia-southeast1-docker.pkg.dev/multi-gke-ops/gke-repo/scraping-job:latest"
        ports:
        - name: http1
          containerPort: 8000
        resources:
          limits:
            cpu: 1
            memory: 1024Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 3
          tcpSocket:
            port: 8000

